"use client"

import BackButton from "@/Components/Reusable/BackButton"
import EquationPageBody from "@/Components/Reusable/EquationPageBody"
import EquationSectionWrapper from "@/Components/Reusable/EquationSectionWrapper"
import GenericPageWrapper from "@/Components/Reusable/GenericPageWrapper"
import Header from "@/Components/Reusable/Header"
import SideNav from "@/Components/Reusable/SideNav"
import Transition from "@/Components/utils/Transition"

const FinanceIntro = () => {
  return (
    <>
    <Transition>
        <main>
            <Header pageHeading="Why firms need finance and sources of finance" pageSubheading="Week 8"/>
            <GenericPageWrapper>
                <BackButton />
                    <EquationSectionWrapper>
                        <EquationPageBody 
                            equationExplanation="
                            <mark>Why might firms need finance?</mark>
                            <br/>
                            <br/>
                            - To purchase long-term assets, like employing people, buying factories etc.
                            <br/>
                            - To finance expansions to production capacity.
                            <br/>
                            - To develop and market new products
                            <br/>
                            - To enter new markets
                            <br/>
                            - To move to new premises
                            <br/>
                            - To pay for daily running of the business
                            <br/>
                            - For takeovers or aquisitions
                            <br/>
                            <br/>
                            <mark>Internal Sources of Finance</mark>
                            <br/>
                            <br/>
                            - Retained earnings
                            <br/>
                            - Trade Credit
                            <br/>
                            - Working capital management
                            <br/>
                            <br/>
                            <mark>Retained Earnings</mark>
                            <br/>
                            <br/>
                            One of the most important sources of corporate long-term investment
                            capital is retained earnings.
                            <br/>
                            <br/>
                            This is that part of net cash flow generated by a company’s past
                            investment projects which is retained within the firm rather than being
                            distributed to shareholders.
                            <br/>
                            <br/>
                            <mark>Advantages of Retained Earnings</mark>
                            <br/>
                            <br/>
                            - No dilution of control and ownership
                            <br/>
                            - No fixed obligation or interest or installment payments
                            <br/>
                            - No issue cost attached
                            <br/>
                            <br/>
                            <mark>Cost of Retained Earnings</mark>
                            <br/>
                            <br/>
                            Because retained earnings arise from sources internal to the company, 
                            there is a temptation to believe that this source of capital is somehow costless.
                            <br/>
                            <br/>
                            In fact, both from a legal and economic standpoint, retained earnings belong to 
                            the ordinary shareholders of a company and so the 'cost' of retained earnings is exactly
                            the same as the expected return required by shareholders on new equity: the cost of equity capital.
                            <br/>
                            <br/>
                            <mark>Trade Credit</mark>
                            <br/>
                            <br/>
                            Trade creditors are often considered as a 'free' source of internal finance.
                            <br/>
                            <br/>
                            This is not correct, as extended payment terms (which may be negotiated with suppliers)
                            include a cost (usually included into the selling price charged). 
                            <br/>
                            <br/>
                            Hence, accounts payable are a source of finance but it is not free.
                            <br/>
                            <br/>
                            <mark>Working Capital Management</mark>
                            <br/>
                            <br/>
                            Working capital involves current assets and current liabilities.
                            <br/>
                            <br/>
                            A reduction in working capital (which can be achieved by speeding up 
                                the cycle of accounts receivables and stock or by lengthening the 
                                cycle of accounts payable) can work as internal source of finance, because 
                                funds invested for working capital can be used for other purposes.
                                <br/>
                                <br/>
                            Hence, an efficient management of working capital helps to achieve this. 
                            <br/>
                            <br/>
                            <mark>External Sources of Finance</mark>
                            <br/>
                            <br/>
                            Short term: 
                            <br/>
                            - Overdrafts
                            <br/>
                            - Short term loans and leasing
                            <br/>
                            <br/>
                            Long Term:
                            <br/>
                            - Ordinary shares (or Equity Shares)
                            <br/>
                            - Preference shares
                            <br/>
                            - Financial Debt (including bank loans, debentures etc)
                            <br/>
                            - Bonds
                            <br/>
                            <br/>
                            <mark>Overdrafts, Short-Term Loans and Leasing</mark>
                            <br/>
                            <br/>
                            A bank overdraft is borrowing from bank on a current account.
                            The maximum overdraft allowed is agreed with the bank, and interest
                            is charged on the amount borrowed. In addition, there is also an initial
                            fee for setting up an overdraft facility, and an annual fee for its re-
                            negotiation and administration.
                            <br/>
                            <br/>
                            Firms may occasionally obtain short-term loans from banks, repayable within 
                            one year. The elements of overdrafts, short-term loans and leases will be shown
                            under the current liabilities.
                            <br/>
                            <br/>
                            However, loans and financial leases are generally source of long-term finance
                            (expected to be patyable after one year of the balance sheet date).
                            "
                        />
                    </EquationSectionWrapper>
                <SideNav />
            </GenericPageWrapper>
        </main>
    </Transition>
    </>
  )
}

export default FinanceIntro